### ISSUE TITLE
QPALM not registered

### ISSUE THREAD

**Issue by el-oso** [kul-forbes/QPALM.jl#10]
Hi guys,
it seems that you haven't registered QPALM on the General registry, but you install instruction assume that that is the case.

Could you register it?

**Comment by lostella** [comment]
@el-oso the ball is rolling: https://github.com/JuliaRegistries/General/pull/63249

**Comment by lostella** [comment]
Package is registered; closing

**Comment by el-oso** [comment]
Amazing! Thank you so much
