### ISSUE TITLE
Automatically resolve binary dependency 

### ISSUE THREAD

**Issue by lostella** [kul-forbes/QPALM.jl#2]
The QPALM’s shared library is currently installed manually in the Julia package. We need to make it either automatically built, or fetched from some binary repository (e.g. Bintray)

**Comment by Benny44** [comment]
The binaries for Linux and MacOS should now be available on Bintray, as mentioned in the documentation (https://benny44.github.io/QPALM/). These binaries were compiled against suitesparse from conda (https://anaconda.org/conda-forge/suitesparse).

**Comment by Benny44** [comment]
I spoke a bit too soon, because I get File not found from bintray. Maybe the bintray server needs some time. Otherwise, I am leaving for holidays now and will fix this asap when I am back.

**Comment by Benny44** [comment]
The bintray links (https://bintray.com/benny44/generic/QPALM/1.0#files/) should now work for Linux/ MacOS and Windows. Let me know if they don't. Otherwise, you can close this issue. Cheers.

**Comment by lostella** [comment]
@Benny44 thanks for this. I'll try out #4 and add the appropriate package setup before closing the issue.

**Comment by lostella** [comment]
Solved by #7
